fix broken indentation
Trico-Everfire/p2-publishing-tool pull request #7
Opened 2022-03-04 10:30 UTC by ENDERZOMBI102

2022-03-05 12:54 UTC, ENDERZOMBI102 commented
@craftablescience plz fix

2022-04-01 20:49 UTC, craftablescience requested changes

2022-04-01 20:49 UTC, craftablescience commented on P2Publish.cpp
> +#ifdef WIN32
Should be `_WIN32` for maximum portability

2022-04-01 20:49 UTC, craftablescience commented on P2Publish.cpp
> +	#ifdef NDEBUG
Can be reduced to `#if defined(_WIN32) && defined(NDEBUG)`

2022-04-01 21:12 UTC, craftablescience approved these changes

2022-04-01 21:42 UTC, merged